#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » FanVPN-Store
# Email      » HurufKapital58@gmail.com
# telegram   » https://t.me/AJW29
# whatsapp   » wa.me/+6287812264674
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FanVPN-Store

colornow=$(cat /etc/rmbl/theme/color.conf)
NC="\e[0m"
RED="\033[0;31m"
COLOR1="$(cat /etc/rmbl/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/rmbl/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'

ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Pemulaajiw/script/main/register"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e ""
    echo -e "$COLOR1│            ${COLOR1}PERMISSION DENIED !${NC}"
    echo -e "$COLOR1│   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "$COLOR1│     \033[0;33mBuy access permissions for scripts just 1 usd 2ip ${NC}"
    echo -e "$COLOR1│             \033[0;33mContact Admin :${NC}"
    echo -e "$COLOR1│      ${COLOR1}WhatsApp${NC} wa.me/+6287812264674"
    echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    exit 0
  fi
}
checking_sc
clear

BICyan='\033[1;36m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
BIYellow='\033[1;93m'     # Yellow

echo -e ""
echo -e " $COLOR1 ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${NC}"
echo -e " $COLOR1│${NC} ${COLBG1}              ${WH}• TROJAN PANEL MENU •               ${NC} $COLOR1│ $NC"
echo -e " $COLOR1 ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e " $COLOR1 ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}01${WH}]${NC} ${COLOR1}• ${WH} Create Account Trojan WS/GRPC${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}02${WH}]${NC} ${COLOR1}• ${WH} Create Trial Trojan WS/GRPC${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}03${WH}]${NC} ${COLOR1}• ${WH} Delete Account Trojan WS/GRPC${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}04${WH}]${NC} ${COLOR1}• ${WH} Renew Trojan Account${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}05${WH}]${NC} ${COLOR1}• ${WH} Check Trojan login Account${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}06${WH}]${NC} ${COLOR1}• ${WH} Check Trojan Config Account${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}07${WH}]${NC} ${COLOR1}• ${WH} Recovery Trojan Account${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}08${WH}]${NC} ${COLOR1}• ${WH} Edit-IP Trojan Limit Account${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}09${WH}]${NC} ${COLOR1}• ${WH} Edit-BW Trojan Limit Account${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}10${WH}]${NC} ${COLOR1}• ${WH} Locked Trojan User Account${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}11${WH}]${NC} ${COLOR1}• ${WH} Unlocked Trojan User Account${NC}"
echo -e " $COLOR1│ $NC    ${WH}[${COLOR1}0X${WH}]${NC} ${COLOR1}• ${WH} ComeBack Menu${NC}"
echo -e " $COLOR1 ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛${NC}"
echo -e " $COLOR1╭═══════════════════════ ${WH}BY${NC} ${COLOR1}═════════════════════════╮ ${NC}"
echo -e " $COLOR1│${NC}                ${WH}• FAN vpn STORES •                  ${NC} $COLOR1│ $NC"
echo -e " $COLOR1╰════════════════════════════════════════════════════╯${NC}"
echo -e ""
read -p "  Select From Options [ 1-6 / 0X ] »» " menu

case $menu in
1 | 01)
    addtr
    ;;
2 | 02)
    trialtr
    ;;
3 | 03)
    deltr
    ;;
4 | 04)
    renewtr
    ;;
5 | 05)
    cektr
    ;;
6 | 06)
    list-trojan
    ;;
7 | 07)
    recover-tr
    ;;
8 | 08)
    ganti-ip-trojan
    ;;
9 | 09)
    trojan-qouta
    ;;
10)
    lock-tr
    ;;
11)
    unlock-tr
    ;;
0 | 00 | x | X | 0x | 0X)
    clear
    menu
    ;;    
*)
    m-trojan
    ;;
esac
