#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » FanVPN-Store
# Email      » HurufKapital58@gmail.com
# telegram   » https://t.me/AJW29
# whatsapp   » wa.me/+6287812264674
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FanVPN-Store

colornow=$(cat /etc/rmbl/theme/color.conf)
NC="\e[0m"
RED="\033[0;31m"
BRED="\e[41m"
COLOR1="$(cat /etc/rmbl/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/rmbl/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
OK="${GREEN}[OK]${NC}"
Error="${RED}[Mistake]${NC}"

ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Pemulaajiw/script/main/register"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e ""
    echo -e "$COLOR1│            ${COLOR1}PERMISSION DENIED !${NC}"
    echo -e "$COLOR1│   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "$COLOR1│     \033[0;33mBuy access permissions for scripts just 1 usd 2ip ${NC}"
    echo -e "$COLOR1│             \033[0;33mContact Admin :${NC}"
    echo -e "$COLOR1│      ${COLOR1}WhatsApp${NC} wa.me/+6287812264674"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    exit 0
  fi
}
checking_sc
clear

BICyan='\033[1;36m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
BIYellow='\033[1;93m'     # Yellow

echo -e ""
echo -e "$COLOR1  ╔═══════════════════════════════════════════════════════════════════════╗$NC"
echo -e "$COLOR1  ║$NC $BRED                           XRAYS-MultiPort                           $COLOR1 ║"
echo -e "$COLOR1  ╚═══════════════════════════════════════════════════════════════════════╝$NC"
echo -e "$COLOR1  ╔═══════════════════════════════════╦═══════════════════════════════════╗"
echo -e "$COLOR1  ║ $WH        ✶ VMESS WS/GRPC ✶  $COLOR1       ║  $WH      ✶ VLESS WS/GRPC ✶       $COLOR1   ║"
echo -e "$COLOR1  ║-----------------------------------║-----------------------------------║"
echo -e "$COLOR1  ╠➣$NC 1.  Create Account XRAYS Vmess $COLOR1  ╠➣$NC 12. Create Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ╠➣$NC 2.  Trial  Account XRAYS Vmess $COLOR1  ╠➣$NC 13. Trial  Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ╠➣$NC 3.  Delete Account XRAYS Vmess $COLOR1  ╠➣$NC 14. Delete Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ╠➣$NC 4.  Rennew Account XRAYS Vmess $COLOR1  ╠➣$NC 15. Rennew Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ╠➣$NC 5.  Login  Account XRAYS Vmess $COLOR1  ╠➣$NC 16. Login  Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ╠➣$NC 6.  Config Account XRAYS Vmess $COLOR1  ╠➣$NC 17. Config Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ╠➣$NC 7.  Recver Account XRAYS Vmess $COLOR1  ╠➣$NC 18. Recver Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ╠➣$NC 8.  EditIP Account XRAYS Vmess $COLOR1  ╠➣$NC 19. EditIP Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ╠➣$NC 9.  EditBW Account XRAYS Vmess $COLOR1  ╠➣$NC 20. EditBW Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ╠➣$NC 10. Locked Account XRAYS Vmess $COLOR1  ╠➣$NC 21. Locked Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ╠➣$NC 11. Unlock Account XRAYS Vmess $COLOR1  ╠➣$NC 22. Unlock Account XRAYS VLESS $COLOR1  ║ "
echo -e "$COLOR1  ║-----------------------------------║-----------------------------------║"
echo -e "$COLOR1  ╚═══════════════════════════════════╩═══════════════════════════════════╝$NC"
echo -e "$COLOR1  ╔═══════════════════════════════════╦═══════════════════════════════════╗"
echo -e "$COLOR1  ║$WH         ✶ TROJAN WS/GRPC ✶ $COLOR1       ║$WH     ✶ SHADOWSOCKS WS/GRPC ✶       $COLOR1║"
echo -e "$COLOR1  ║-----------------------------------║-----------------------------------║"
echo -e "$COLOR1  ╠➣$NC 23. Create Account XRAYS Trojan $COLOR1 ╠➣$NC 19. Create Account ShadowSocks $COLOR1  ║"
echo -e "$COLOR1  ╠➣$NC 24. Trial  Account XRAYS Trojan $COLOR1 ╠➣$NC 20. Trial  Account ShadowSocks $COLOR1  ║"
echo -e "$COLOR1  ╠➣$NC 25. Delete Account XRAYS Trojan $COLOR1 ╠➣$NC 21. Delete Account ShadowSocks $COLOR1  ║"
echo -e "$COLOR1  ╠➣$NC 26. Rennew Account XRAYS Trojan $COLOR1 ╠➣$NC 22. Rennew Account ShadowSocks $COLOR1  ║"
echo -e "$COLOR1  ╠➣$NC 27. Login  Account XRAYS Trojan $COLOR1 ╠➣$NC 23. Login  Account ShadowSocks $COLOR1  ║"
echo -e "$COLOR1  ╠➣$NC 28. Config Account XRAYS Trojan $COLOR1 ╠➣$NC 24. Config Account ShadowSocks $COLOR1  ║"
echo -e "$COLOR1  ╠➣$NC 28. Recver Account XRAYS Trojan $COLOR1
echo -e "$COLOR1  ╠➣$NC 28. EditIP Account XRAYS Trojan $COLOR1
echo -e "$COLOR1  ╠➣$NC 28. EditBW Account XRAYS Trojan $COLOR1
echo -e "$COLOR1  ╠➣$NC 28. Locked Account XRAYS Trojan $COLOR1
echo -e "$COLOR1  ╠➣$NC 28. Unlock Account XRAYS Trojan $COLOR1
echo -e "$COLOR1  ║                                 $COLOR1  ╠➣$NC 0X. Back To Menu              $COLOR1   ║ "
echo -e "$COLOR1  ║-----------------------------------║-----------------------------------║"
echo -e "$COLOR1  ╚═══════════════════════════════════╩═══════════════════════════════════╝$NC"
echo -e " $COLOR1 ╭═══════════════════════ ${WH}BY${NC} ${COLOR1}═════════════════════════╮ ${NC}"
echo -e " $COLOR1 │${NC}                ${WH}• FAN vpn STORES •                  ${NC} $COLOR1│ $NC"
echo -e " $COLOR1 ╰════════════════════════════════════════════════════╯${NC}"
echo -e ""
read -p "  Select From Options [ 1-24 / 0X ] »» " menu

case $menu in
1 | 01) clear ;
    addws
    ;;
2 | 02) clear ;
    trialws
    ;;
3 | 03) clear ;
    delws
    ;;
4 | 04) clear ;
    renewws
    ;;
5 | 05) clear ;
    cekws
    ;;
6 | 06) clear ;
    list-vmess
    ;;
7 | 07) clear ;
    addvless
    ;;
8 | 08) clear ;
    trialvless
    ;;
9 | 09) clear ;
    delvless
    ;;
10) clear ;
    renewvless
    ;;
11) clear ;
    cekvless
    ;;
12) clear ;
    list-vless
    ;;
13)
    addtr
    ;;
14)
    trialtr
    ;;
15)
    deltr
    ;;
16)
    renewtr
    ;;
17)
    cektr
    ;;
18)
    list-trojan
    ;;
19)
    addss
    ;;
20)
    trialss
    ;;
21)
    delss
    ;;
22)
    renewss
    ;;
23)
    cekss
    ;;
24)
    list-ssws
    ;;
0 | 00 | x | X | 0x | 0X)
    clear
    menu
    ;; 
*)  clear ;
    m-vmess
    ;;    
esac
